In [33]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix ,classification_report
from sklearn.ensemble import RandomForestClassifier

In [2]:
df=pd.read_csv("C:/Users/siddh/dataset.csv")
df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.tail()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
4915,(vertigo) Paroymsal Positional Vertigo,vomiting,headache,nausea,spinning_movements,loss_of_balance,unsteadiness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4916,Acne,skin_rash,pus_filled_pimples,blackheads,scurring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4917,Urinary tract infection,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4918,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4919,Impetigo,skin_rash,high_fever,blister,red_sore_around_nose,yellow_crust_ooze,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_desc=pd.read_csv("C:/Users/siddh/symptom_Description.csv")
df_prec=pd.read_csv("C:/Users/siddh/symptom_precaution.csv")
df_sev=pd.read_csv("C:/Users/siddh/Symptom-severity.csv")

In [5]:
df_desc.head()

          Disease                                        Description
0   Drug Reaction  An adverse drug reaction (ADR) is an injury ca...
1         Malaria  An infectious disease caused by protozoan para...
2         Allergy  An allergy is an immune system response to a f...
3  Hypothyroidism  Hypothyroidism, also called underactive thyroi...
4       Psoriasis  Psoriasis is a common skin disorder that forms...

In [6]:
df_desc.tail()

            Disease                                        Description
36     Heart attack  The death of heart muscle due to the loss of b...
37        Pneumonia  Pneumonia is an infection in one or both lungs...
38        Arthritis  Arthritis is the swelling and tenderness of on...
39  Gastroenteritis  Gastroenteritis is an inflammation of the dige...
40     Tuberculosis  Tuberculosis (TB) is an infectious disease usu...

In [7]:
df_prec.head()

,Disease,Precaution_1,Precaution_2,Precaution_3,Precaution_4
0,Drug Reaction,stop irritation,consult nearest hospital,stop taking drug,follow up
1,Malaria,Consult nearest hospital,avoid oily food,avoid non veg food,keep mosquitos out
2,Allergy,apply calamine,cover area with bandage,NaN,use ice to compress itching
3,Hypothyroidism,reduce stress,exercise,eat healthy,get proper sleep
4,Psoriasis,wash hands with warm soapy water,stop bleeding using pressure,consult doctor,salt baths

In [8]:
df_prec.tail()

,Disease,Precaution_1,Precaution_2,Precaution_3,Precaution_4
36,Heart attack,call ambulance,chew or swallow asprin,keep calm,NaN
37,Pneumonia,consult doctor,medication,rest,follow up
38,Arthritis,exercise,use hot and cold therapy,try acupuncture,massage
39,Gastroenteritis,stop eating solid food for while,try taking small sips of water,rest,ease back into eating
40,Tuberculosis,cover mouth,consult doctor,medication,rest

In [9]:
df_sev.head()

                Symptom  weight
0               itching       1
1             skin_rash       3
2  nodal_skin_eruptions       4
3   continuous_sneezing       4
4             shivering       5

In [10]:
df_sev.tail()

                  Symptom  weight
128    inflammatory_nails       2
129               blister       4
130  red_sore_around_nose       2
131     yellow_crust_ooze       3
132             prognosis       5

In [11]:
df=df.replace(np. nan,'Asymtomatic',regex=True)
df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
3,Fungal infection,itching,skin_rash,dischromic _patches,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic

In [12]:
df_prec=df_prec.replace(np. nan,'no precaution',regex=True)
df_prec.head()

,Disease,Precaution_1,Precaution_2,Precaution_3,Precaution_4
0,Drug Reaction,stop irritation,consult nearest hospital,stop taking drug,follow up
1,Malaria,Consult nearest hospital,avoid oily food,avoid non veg food,keep mosquitos out
2,Allergy,apply calamine,cover area with bandage,no precaution,use ice to compress itching
3,Hypothyroidism,reduce stress,exercise,eat healthy,get proper sleep
4,Psoriasis,wash hands with warm soapy water,stop bleeding using pressure,consult doctor,salt baths

In [13]:
for ind in df_sev.index:
    continue

In [14]:
data_dict = df_sev.set_index('Symptom').T.to_dict()

C:\Users\siddh\AppData\Local\Temp\ipykernel_1828\3666179390.py:1: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  data_dict = df_sev.set_index('Symptom').T.to_dict()

In [15]:
def remove_space_between_word(dataset):
    for col in dataset.columns:
        for i in range(len(dataset[col])):
            if (type(dataset[col][i]) == str ):
                dataset[col][i] = dataset[col][i].strip()
                dataset[col][i] = dataset[col][i].replace(" ", "_")
    return dataset

In [16]:
new_df = remove_space_between_word(df)

In [17]:
new_df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal_infection,itching,skin_rash,nodal_skin_eruptions,dischromic__patches,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
1,Fungal_infection,skin_rash,nodal_skin_eruptions,dischromic__patches,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
2,Fungal_infection,itching,nodal_skin_eruptions,dischromic__patches,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
3,Fungal_infection,itching,skin_rash,dischromic__patches,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
4,Fungal_infection,itching,skin_rash,nodal_skin_eruptions,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic

In [18]:
new_df=new_df.replace(np. nan,'no precaution',regex=True)
new_df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal_infection,itching,skin_rash,nodal_skin_eruptions,dischromic__patches,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
1,Fungal_infection,skin_rash,nodal_skin_eruptions,dischromic__patches,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
2,Fungal_infection,itching,nodal_skin_eruptions,dischromic__patches,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
3,Fungal_infection,itching,skin_rash,dischromic__patches,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
4,Fungal_infection,itching,skin_rash,nodal_skin_eruptions,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic

In [19]:
def enc(dataset):
    for ind in df_sev.index:
        dataset = dataset.replace(df_sev["Symptom"][ind] , df_sev["weight"][ind])
    dataset = dataset.fillna(0) # put empty cell to 0
    dataset = dataset.replace("foul_smell_of_urine" , 5)
    dataset = dataset.replace("dischromic__patches" , 6)
    dataset = dataset.replace("spotting__urination" , 6)
    return dataset

In [37]:
print(data_dict["foul_smell_ofurine"])
print(data_dict["dischromic_patches"])
print(data_dict["spotting_urination"])

{'weight': 5}
{'weight': 6}
{'weight': 6}

In [38]:
df = encode_data(new_df , data_dict)
df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal_infection,1,3,4,6,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
1,Fungal_infection,3,4,6,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
2,Fungal_infection,1,4,6,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
3,Fungal_infection,1,3,6,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
4,Fungal_infection,1,3,4,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic

In [39]:
df=df.replace('Asymtomatic', 0 ,regex=True)
df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal_infection,1,3,4,6,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Fungal_infection,3,4,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Fungal_infection,1,4,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Fungal_infection,1,3,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Fungal_infection,1,3,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [40]:
def encode_data(dataset , data_dict_weigth):
    cols = dataset.columns
    for columnName in cols:
        for i in range(len(dataset[columnName])):
            try:
            #print(data_dict[data2[columnName][i]]["weight"])
                dataset[columnName][i] = data_dict[dataset[columnName][i]]["weight"]
            except:
                pass
    dataset = dataset.fillna(0) # put empty cell to 0
    dataset = dataset.replace("foul_smell_of_urine" , 5)
    dataset = dataset.replace("dischromic__patches" , 6)
    dataset = dataset.replace("spotting__urination" , 6)
    return dataset

In [41]:
df_f = encode_data(new_df , data_dict)
df_f.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal_infection,1,3,4,6,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
1,Fungal_infection,3,4,6,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
2,Fungal_infection,1,4,6,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
3,Fungal_infection,1,3,6,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic
4,Fungal_infection,1,3,4,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic,Asymtomatic

In [42]:
df_f=df_f.replace('Asymtomatic', 0 ,regex=True)
df_f.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal_infection,1,3,4,6,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Fungal_infection,3,4,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Fungal_infection,1,4,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Fungal_infection,1,3,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Fungal_infection,1,3,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [43]:
df_f=df_f.replace('no precaution', 0 ,regex=True)
df_f.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal_infection,1,3,4,6,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Fungal_infection,3,4,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Fungal_infection,1,4,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Fungal_infection,1,3,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Fungal_infection,1,3,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [44]:
names = []
for col in df.columns:
    if(col != "Disease"):
        for i in range(len(df[col])):
            if (type(df[col][i]) == str ):
                if df[col][i] not in names :
                    names.append(df[col][i])
                    
print(" no replace are :" , names)

 no replace are : []

In [45]:
df_data = df_f.drop('Disease' , axis =1)
label = df_f["Disease"]

In [46]:
x_train, x_test, y_train, y_test = train_test_split(df_data, label, shuffle=True, train_size = 0.70)
randomFC = RandomForestClassifier()
randomFC.fit(x_train, y_train)
result = randomFC.predict(x_test)
print(randomFC)
print(classification_report(y_true=y_test, y_pred=result))
print('F1-score% =', f1_score(y_test, result, average='macro')*100, '|', 'Accuracy% =', accuracy_score(y_test, result)*100)

RandomForestClassifier()
                                         precision    recall  f1-score   support

(vertigo)_Paroymsal__Positional_Vertigo       1.00      1.00      1.00        39
                                   AIDS       1.00      1.00      1.00        42
                                   Acne       1.00      1.00      1.00        31
                    Alcoholic_hepatitis       1.00      1.00      1.00        26
                                Allergy       0.86      1.00      0.92        36
                              Arthritis       1.00      1.00      1.00        34
                       Bronchial_Asthma       1.00      1.00      1.00        35
                   Cervical_spondylosis       0.94      1.00      0.97        33
                            Chicken_pox       1.00      1.00      1.00        40
                    Chronic_cholestasis       1.00      1.00      1.00        35
                            Common_Cold       1.00      1.00      1.00        30
                                 Dengue       1.00      1.00      1.00        37
                               Diabetes       1.00      1.00      1.00        30
           Dimorphic_hemmorhoids(piles)       1.00      1.00      1.00        38
                          Drug_Reaction       1.00      1.00      1.00        38
                       Fungal_infection       0.91      1.00      0.95        39
                                   GERD       1.00      1.00      1.00        39
                        Gastroenteritis       1.00      0.84      0.91        37
                           Heart_attack       1.00      1.00      1.00        32
                            Hepatitis_B       1.00      1.00      1.00        31
                            Hepatitis_C       1.00      1.00      1.00        33
                            Hepatitis_D       1.00      1.00      1.00        42
                            Hepatitis_E       1.00      1.00      1.00        33
                           Hypertension       0.97      0.95      0.96        38
                        Hyperthyroidism       1.00      1.00      1.00        36
                           Hypoglycemia       1.00      1.00      1.00        32
                         Hypothyroidism       1.00      1.00      1.00        35
                               Impetigo       1.00      0.98      0.99        42
                               Jaundice       1.00      1.00      1.00        30
                                Malaria       1.00      1.00      1.00        40
                               Migraine       1.00      1.00      1.00        38
                        Osteoarthristis       1.00      1.00      1.00        34
           Paralysis_(brain_hemorrhage)       1.00      0.91      0.96        47
                    Peptic_ulcer_diseae       1.00      1.00      1.00        36
                              Pneumonia       1.00      1.00      1.00        30
                              Psoriasis       1.00      1.00      1.00        39
                           Tuberculosis       1.00      1.00      1.00        33
                                Typhoid       1.00      1.00      1.00        42
                Urinary_tract_infection       1.00      1.00      1.00        34
                         Varicose_veins       1.00      1.00      1.00        48
                            hepatitis_A       1.00      1.00      1.00        32

                               accuracy                           0.99      1476
                              macro avg       0.99      0.99      0.99      1476
                           weighted avg       0.99      0.99      0.99      1476

F1-score% = 99.17111399812923 | Accuracy% = 99.11924119241192

In [47]:
qw=pd.DataFrame([[1,2,3,4,5,6,1,2,3,4,5,6,1,2,3,4,5]],columns=['Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4', 'Symptom_5',
       'Symptom_6', 'Symptom_7', 'Symptom_8', 'Symptom_9', 'Symptom_10',
       'Symptom_11', 'Symptom_12', 'Symptom_13', 'Symptom_14', 'Symptom_15',
       'Symptom_16', 'Symptom_17'])

In [48]:
x_train.columns

Index(['Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4', 'Symptom_5',
       'Symptom_6', 'Symptom_7', 'Symptom_8', 'Symptom_9', 'Symptom_10',
       'Symptom_11', 'Symptom_12', 'Symptom_13', 'Symptom_14', 'Symptom_15',
       'Symptom_16', 'Symptom_17'],
      dtype='object')

In [49]:
output = randomFC.predict(qw)

In [50]:
output[0]

'Hepatitis_B'

In [51]:
import pickle

In [52]:
filename='model.pkl'
pickle.dump(randomFC,open(filename,'wb'))

In [53]:
clff=pickle.load(open('model.pkl','rb'))

In [54]:
result = clff.predict(x_test)
print(classification_report(y_true=y_test, y_pred=result))
print('F1-score% =', f1_score(y_test, result, average='macro')*100, '|', 'Accuracy% =', accuracy_score(y_test, result)*100)

                                         precision    recall  f1-score   support

(vertigo)_Paroymsal__Positional_Vertigo       1.00      1.00      1.00        39
                                   AIDS       1.00      1.00      1.00        42
                                   Acne       1.00      1.00      1.00        31
                    Alcoholic_hepatitis       1.00      1.00      1.00        26
                                Allergy       0.86      1.00      0.92        36
                              Arthritis       1.00      1.00      1.00        34
                       Bronchial_Asthma       1.00      1.00      1.00        35
                   Cervical_spondylosis       0.94      1.00      0.97        33
                            Chicken_pox       1.00      1.00      1.00        40
                    Chronic_cholestasis       1.00      1.00      1.00        35
                            Common_Cold       1.00      1.00      1.00        30
                                 Dengue       1.00      1.00      1.00        37
                               Diabetes       1.00      1.00      1.00        30
           Dimorphic_hemmorhoids(piles)       1.00      1.00      1.00        38
                          Drug_Reaction       1.00      1.00      1.00        38
                       Fungal_infection       0.91      1.00      0.95        39
                                   GERD       1.00      1.00      1.00        39
                        Gastroenteritis       1.00      0.84      0.91        37
                           Heart_attack       1.00      1.00      1.00        32
                            Hepatitis_B       1.00      1.00      1.00        31
                            Hepatitis_C       1.00      1.00      1.00        33
                            Hepatitis_D       1.00      1.00      1.00        42
                            Hepatitis_E       1.00      1.00      1.00        33
                           Hypertension       0.97      0.95      0.96        38
                        Hyperthyroidism       1.00      1.00      1.00        36
                           Hypoglycemia       1.00      1.00      1.00        32
                         Hypothyroidism       1.00      1.00      1.00        35
                               Impetigo       1.00      0.98      0.99        42
                               Jaundice       1.00      1.00      1.00        30
                                Malaria       1.00      1.00      1.00        40
                               Migraine       1.00      1.00      1.00        38
                        Osteoarthristis       1.00      1.00      1.00        34
           Paralysis_(brain_hemorrhage)       1.00      0.91      0.96        47
                    Peptic_ulcer_diseae       1.00      1.00      1.00        36
                              Pneumonia       1.00      1.00      1.00        30
                              Psoriasis       1.00      1.00      1.00        39
                           Tuberculosis       1.00      1.00      1.00        33
                                Typhoid       1.00      1.00      1.00        42
                Urinary_tract_infection       1.00      1.00      1.00        34
                         Varicose_veins       1.00      1.00      1.00        48
                            hepatitis_A       1.00      1.00      1.00        32

                               accuracy                           0.99      1476
                              macro avg       0.99      0.99      0.99      1476
                           weighted avg       0.99      0.99      0.99      1476

F1-score% = 99.17111399812923 | Accuracy% = 99.11924119241192